name: Snap
options:
  bundleIdPrefix: com.snap
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  Snap:
    type: application
    platform: macOS
    sources:
      - Snap
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snap.app
        INFOPLIST_FILE: Snap/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Snap/Resources/Snap.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: Snap/Resources/Snap.entitlements
  SnapTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - SnapTests
    dependencies:
      - target: Snap
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snap.tests
        GENERATE_INFOPLIST_FILE: YES
